version: "3.8"

services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    networks:
      - mongors-network
    ports:
      - 27017:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "dbrs", "--bind_ip", "localhost,mongo1"]
  mongo2:
    container_name: mongo2
    image: mongo:latest
    networks:
      - mongors-network
    ports:
      - 27018:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "dbrs", "--bind_ip", "localhost,mongo2"]
  mongo3:
    container_name: mongo3
    image: mongo:latest
    networks:
      - mongors-network
    ports:
      - 27019:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "dbrs", "--bind_ip", "localhost,mongo3"]
networks:
  mongors-network:
